version: "1.0"
info:
  model: int-scaffold
packages:
- name: ACMEProject
  gitServerName: Siddharth_Git
  gitUrl: https://github.com/siddharthsethi11
  gitUsername: siddharthsethi11
  gitBranch: main
